spring:
  application:
    name: concert-reservation-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/concert
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  config: classpath:logback.xml